Repository selsa-inube/inubekit-flag, pull requests merged in 2024-09, with the labels that each got.

#41 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#42 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#43 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#44 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#45 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#46 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#47 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#48 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#49 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#50 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#23 Create `<Flag />` Component and Package, Export All Parts
  CHANGELOG.md
  package.json
  src/Flag/index.tsx
  src/Flag/styles.js
  src/components/Flag/Flag.stories.tsx
  src/components/Flag/index.tsx
  src/components/Flag/props.ts
  src/components/Flag/styles.js
  src/components/FlagPortal/FlagPortal.stories.tsx
  src/components/FlagPortal/index.tsx
  src/components/FlagPortal/styles.js
  src/hooks/useFlag.ts
  src/index.ts
  src/providers/FlagsProvider.tsx
  vite.config.ts
Labels: major

#51 fix(flag): adjust max length in description and flag min-height
  src/components/Flag/index.tsx
  src/components/Flag/styles.js
Labels: patch

#52 feat: extend description max length to 80ch
  src/components/Flag/index.tsx
Labels: minor

#53 Update text dependency to latest version
  package.json
Labels: minor, dependencies

#54 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#55 Update text dependency to latest version
  package.json
Labels: minor, dependencies
