Repository selsa-inube/inubekit-flag, pull requests merged in 2024-04, with the labels that each got.

#8 Add auto publish
  .autorc.json
  .github/workflows/auto-release.yml
  .gitignore
  package-lock.json
  package.json
  src/SectionMessage/SectionMessage.stories.tsx
  src/SectionMessage/index.tsx
  src/SectionMessage/props.ts
  vite.config.ts
Labels: enhancement

#7 Refactor component to use new token structure and expandable mobile
  CHANGELOG.md
  package.json
  src/SectionMessage/SectionMessage.stories.tsx
  src/SectionMessage/index.tsx
  src/SectionMessage/props.ts
  src/SectionMessage/styles.js
Labels: major

#6 Adjust and export interfaces
  CHANGELOG.md
  src/SectionMessage/index.tsx
  src/SectionMessage/props.ts
  src/index.ts
Labels: major

#9 Refactor component (sectionMessage) so it uses theme from ThemeContext
  package.json
  src/SectionMessage/index.tsx
Labels: major

#10 Refactor component (sectionMessage) so it uses theme from ThemeContext
  src/SectionMessage/index.tsx
Labels: minor

#11 Update workflow in order to avoid merges with failed builds
  .github/workflows/auto-release.yml
Labels: minor
